language: cpp
os: 
  #- linux
  - osx
branches:
  only:
    - travis-ci
compiler:
  - clang

git:
  submodules: false # submodule init handled by prep-third-party.sh

cache:
  directories:
    - third-party/ispc/ispc-*
    - third-party/embree
    - third-party/ospray
    - third-party/rapidjson
    - .gxy_third_party_prep_done
    - .gxy_third_party_installed

addons:
  apt:
    packages:
      - libtbb-dev
      - libboost-all-dev
      - mpi-default-dev
      - freeglut3-dev
  homebrew:
    packages: 
      - vtk
      - tbb
      - boost
      - open-mpi
      - freeglut

install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then wget https://www.vtk.org/files/release/8.1/VTK-8.1.2.tar.gz && tar xf VTK-8.1.2.tar.gz && cd VTK-8.1.2 && mkdir build && cmake .. && sudo make -j 8 install; fi
  - scripts/install-third-party.sh

script:
  - mkdir build
  - cd build
  - ls /usr/local/Cellar/freeglut/3.0.0/lib
#  - if [ $TRAVIS_OS_NAME == "osx" ]; then cmake -D GLUT_INCLUDE_DIR:PATH=/usr/local/Cellar/freeglut/3.0.0/include -D GLUT_glut_LIBRARY:FILEPATH=/usr/local/Cellar/freeglut/3.0.0/lib .. && make install
