language: cpp
os: 
  #- linux
  - osx
branches:
  only:
    - travis-ci
compiler:
  - clang

git:
  submodules: false # submodule init handled by prep-third-party.sh

addons:
  apt:
    packages:
      - libtbb-dev
      - libboost-all-dev
      - mpi-default-dev
  homebrew:
    packages: 
      - vtk
      - tbb
      - boost
      - open-mpi

before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then wget https://www.vtk.org/files/release/8.1/VTK-8.1.2.tar.gz && tar xf VTK-8.1.2.tar.gz && cd VTK-8.1.2 && mkdir build && cmake .. && sudo make -j 8 install; fi
  - scripts/install-third-party.sh

install:
  - mkdir build
  - cd build
  - cmake .. && make install
