language: cpp
dist: xenial # get a semi-modern linux

branches:
  only:
    - travis-ci

matrix:
  include:
    # - os: osx
    #   compiler: clang
    #   env:
    #     - MATRIX_EVAL=""

    # - os: osx
    #   compiler: gcc
    #   env:
    #     - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

    - os: linux
      compiler: clang
      env:
        - MATRIX_EVAL=""

    # - os: linux
    #   compiler: gcc
    #   env:
    #     - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"



git:
  submodules: false # submodule init handled by prep-third-party.sh

cache:
  directories:
    - .galaxy
    - third-party/ispc
    - third-party/embree
    - third-party/ospray
    - third-party/rapidjson
    - third-party/VTK-8.1.2

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - libtbb-dev
      - libboost-all-dev
      - mpi-default-dev
      - freeglut3-dev
      - libxrandr-dev
      - libxinerama-dev
      - libxcursor-dev
      - imagemagick
  homebrew:
    packages: 
      - vtk
      - tbb
      - boost
      - open-mpi
      - freeglut
      - imagemagick
      # - gcc@7

before_install:
  - eval "${MATRIX_EVAL}"

script:
  # - rm -rf third-party/VTK-8.1.2 # use to rebuild VTK cache for linux
  - cd third-party/VTK-8.1.2/build && cmake -D VTK_WRAP_PYTHON:BOOL=ON . && make -j 4 install
  # - scripts/do-travis-ci-build.sh
  # - tests/run-image-gold-tests.sh


